#%RAML 1.0 DataType

type: object
properties:
  memberID:
    description: this is contain customer ID
    type: string
    required: true
    example: "mdsbh123"
  transactionID:
    description: this is contain customer transactionID         
    type: string
    required: true
    example: "mdh123"
  amount:
    description: this is contain transaction amount
    type: integer
    required: true
    example: 12345
  memberTier:
    description: this is contain customer tier
    type: string
    required: true
    enum:
    - T1
    - T2
    - T3
    - T4
    example: "T4"
  transactionDate:
    description: this is contain transaction date
    type: string
    required: true
    example: "04-05-2021"