#%RAML 1.0 ResourceType

traits:

  business: /trait/business-trait.raml
  clientIdSecret: /trait/clientIdecret-trait.raml
  transactionId: /trait/transactionId-trait.raml
  Autharization: /trait/autharizationJWTtrait.raml

type:
  errorResponse: /Datatype/error-response-dataType.raml
  