#%RAML 1.0 Trait

headers:
      clientId:
        description: This header contains client id
        type: string
        required: true
        example: "jfhflhligrgrj"
      clientSecret:
        description: This header contains client secret
        type: string
        required: true
        example: "jfhflhligrg"